Fix the build break caused by deprecated declarations from latest version of RocksDB
Summary:
Currently the `{ latest MyRocks + latest RocksDB }` builds fails because `GetApproximateSizes` is marked as `ROCKSDB_DEPRECATED_FUNC`. This causes build errors like:

```
error: ‘virtual void rocksdb::DB::GetApproximateSizes(rocksdb::ColumnFamilyHandle*,
const rocksdb::Range*, int, uint64_t*, bool)’ is deprecated (declared at
.../rocksdb/include/rocksdb/db.h:629) [-Werror=deprecated-declarations]
     &sz, true);
```

This is a quick fix to unblock the integration testing.

Reviewed By: lth, VitaliyLi

Differential Revision: D4458637

fbshipit-source-id: 437f9d3986e